; ************
; * base env *
; ************

[esp32]
platform = ${extra.platform}
build_flags =
    ${env.build_flags}
lib_deps =
    ${env.lib_deps}
    ${extra.lib_deps_builtin}
    ; extend libs only for esp32 based modules here

[esp32c6]
extends = esp32
build_flags =
    ${env.build_flags}
lib_deps =
    ${env.lib_deps}
    ${extra.lib_deps_builtin}
    ; extend libs only for esp32c6 based modules here
