; ************
; * base env *
; ************

[esp32]
extends = env
; build_flags =
;     ${env.build_flags}
; lib_deps =
;     ${env.lib_deps}

[esp32c6]
extends = esp32

; use a custom pioarduino platform version with support for ESP32-C6 and PSRAM
; releases https://github.com/pioarduino/platform-espressif32/releases
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip

; build_flags =
;     ${esp32.build_flags}
; lib_deps =
;     ${esp32.lib_deps}
