[env]
lib_deps =
  SPI
  Wire
  ; button handling library with support for single, double and long clicks
  ; https://registry.platformio.org/libraries/mathertel/OneButton
  mathertel/OneButton @ ^2.6.2

  ; XPowersLib - power management series library for ESP32, including PSRAM power management
  ; https://registry.platformio.org/libraries/lewisxhe/XPowersLib
  lewisxhe/XPowersLib @ ^0.3.3

  ; GFX Library - Core graphics library for displays, providing basic graphics primitives
  ; https://registry.platformio.org/libraries/moononournation/GFX%20Library%20for%20Arduino
  moononournation/GFX Library for Arduino @ ^1.6.5

  ; WiFiManager - WiFi configuration manager for ESP32
  ; https://registry.platformio.org/libraries/tzapu/WiFiManager
  tzapu/WiFiManager @ ^2.0.17