
; This is a template for upload configuration which includes OTA credentials.
;
; Copy this file to the same directory and rename it to upload_config.ini,
; then edit the parameters as needed.
;
; ```sh
; cp upload_config_template.ini upload_config.ini
; ```

[env:esp32_c6_amoled_2_06]
; OTA upload parameters, see https://docs.platformio.org/en/latest/platforms/espressif32.html#authentication-and-upload-options

upload_protocol = espota

; IP address when using OTA upload. Make sure it matches the IP address of the device when it is in AP mode.
; https://docs.platformio.org/en/latest/projectconf/sections/env/options/upload/upload_port.html
upload_port = 192.168.4.1

; upload_speed =

upload_flags =
  ; https://docs.platformio.org/en/latest/platforms/espressif32.html#authentication-and-upload-options
  ; replace 12345678 with yours the same as AP_PSK in credentials.h
  --auth=12345678
