on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Set up python
        uses: actions/setup-python@v6
        with:
          architecture: "x64"
          python-version: "3.x"
      - name: Set version from tag
        run: echo "${{ github.ref_name }}" > version.txt
      - name: Commit and push version.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Set version.txt to ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin HEAD:main || echo "No push needed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      # https://docs.platformio.org/en/latest/core/history.html
      - name: Install PlatformIO core
        run: pip install --upgrade platformio
      - name: Build firmwares
        run: FIRMWARE_VERSION=${{github.ref_name}} pio run
      - name: Archive
        uses: actions/upload-artifact@v7
        with:
          name: firmware
          path: .pio/build/*/firmware_*.bin
          retention-days: 1
  release:
    name: Release
    # if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for CHANGELOG
        uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: firmware
          path: firmware
      # - name: Display structure of downloaded files
      #   run: ls -R
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "firmware/*/firmware_*.bin"
          bodyFile: "CHANGELOG.md"
